### ISSUE TITLE
Inconvenientes en la Autoselección de Reportes

### ISSUE THREAD

**Issue by darmandovargas** [darmandovargas/redh#2]
Revisar estaciones que no autoseleccionan sus reportes al ser seleccionadas.

**Comment by darmandovargas** [comment]
Buena noche Camilo

Podría describirme cuales estaciones están presentando el inconveniente ?

Podría por favor decirme si las estaciones de wunderground tienen reportes en la plataforma ? o cómo debería ser su atoselección ? sino existen asumo que no debe existir autoselección, déjeme saber.

Diego Vargas

**Comment by jcamilob86** [comment]
Diego, le copio un achivo de excel con las estaciones con problemas.
[Estado de las estaciones-Valentina.xlsx](https://github.com/darmandovargas/redh/files/2496251/Estado.de.las.estaciones-Valentina.xlsx)

Por otro lado, las estaciones de wunderground no tiene reportes, solo es para visualizar los datos en tiempo real.

**Comment by darmandovargas3** [comment]
Gracias por la información Camilo, voy a revisarlas una por una para saber que sucedió y le dejo saber.

Ok perfecto entonces no es necesario la autoselección en las de wunderground.

**Comment by darmandovargas3** [comment]
Buena tarde

A continuación adjunto archivo con el reporte de la autoselección de los reportes de manera automática que han sido reparados, en conclusión, se empieza a notar la necesidad de una administración de las carpetas y sus relaciones con las estaciones de manera gráfica para minimizar inconvenientes similares que fundamentalmente se originan en inconvenientes en los nombres de las carpetas y diferencias con las definiciones de las mismas, además de cambios en las estaciones y tablas que afectan el id original de las mismas, por lo cual se empieza a ver la necesidad de la automatización de ésta administración.

[Estado.de.las.estaciones-Valentina.xlsx](https://github.com/darmandovargas/redh/files/2496814/Estado.de.las.estaciones-Valentina.xlsx)

Encontrará dos nuevas columnas al final con el reporte de todas las estaciones las cuales han sido probadas, si persiste el inconveniente con alguna, por favor limpie la caché de su navegador e intente de nuevo.

La próxima semana revisamos el tema de la galería de fotos supongo que sobre éstas mismas estaciones.

Diego Vargas

**Comment by darmandovargas** [comment]
Buena noche Camilo

Quedo atento a su confirmación de funcionamiento con el fin de cerrar el ticket.

Diego Vargas
