### ISSUE TITLE
Revisar Estaciones que no Muestran Imágenes

### ISSUE THREAD

**Issue by darmandovargas** [darmandovargas/redh#3]
Revisar estaciones que no muestran las imágenes que se le suben a la galería.

**Comment by darmandovargas** [comment]
Buena noche Camilo

Podría por favor describirme puntualmente cuales estaciones están presentando el inconveniente ?

Puede adjuntar imágenes si lo desea copiándolas y pegándolas acá en un comentario.

Diego Vargas

**Comment by jcamilob86** [comment]
Diego en el otro archivo de excel también esta esta información

**Comment by darmandovargas** [comment]
Buen día Camilo

Adjunto excel con el reporte de cada una de las estaciones que me envió, todas están funcionales ahora, solo falta que agregue las imágenes para que se muestre en muchas de ellas, se realizó algunos ajustes como cuando encontraba un archivo llamado . o .. los cuales realmente no existen o cuando no hay carpeta definida, para que muestre la imagen que informa que no hay fotos para ésta estación.

[Estado.de.las.estaciones-Valentina.xlsx](https://github.com/darmandovargas/redh/files/2513183/Estado.de.las.estaciones-Valentina.xlsx)

Diego Vargas

**Comment by darmandovargas** [comment]
Es altamente recomendable la implementación de la administración de estaciones en donde se pueda definir el nombre de la carpeta, si es pública o no entre muchos otros detalles relevantes, lo cual se expondrá en la propuesta que se le está construyendo para la restauración del sitio.
